/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pruebas;

import Objetos.*;

/**
 *
 * @author USUARIO
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista1() {
        initComponents();
        cargarTablas();
        cargarComboBox();
    }

    // paso4 llamar a los metodos de controlador para cargar las tablas y combox
    public void cargarTablas() {
        Controlador con = new Controlador();
        jtRol.removeAll();
        con.cargarRol(jtRol);
        con.cargarUsuario(jtUsuario);
        con.cargarCiudad(jtCiudad);
        con.cargarCooperativa(jtCop);
        con.cargarBus(jtBus);
        con.cargarCliente(jtCliente);
        con.cargarAsiento(jtAsiento);
        con.cargarRuta(jtRuta);
        con.cargarUsuario(jtUsuario);
    }

    public void cargarComboBox() {
        cbRol.removeAllItems();
        Controlador con = new Controlador();
        con.cargarComboRol(cbRol);
        cbBusCop.removeAllItems();
        con.cargarComboCooperativa(cbBusCop);
        cbAsBus.removeAllItems();
        con.cargarComboBus(cbAsBus);
        cbRtBus.removeAllItems();
        con.cargarComboBus(cbRtBus);
        cbRtUsu.removeAllItems();
        con.cargarComboUsuario(cbRtUsu);
        cbRtCO.removeAllItems();
        con.cargarComboCiudad(cbRtCO);
        cbRtCD.removeAllItems();
        con.cargarComboCiudad(cbRtCD);

        
        

    }
    
    public void devolverDatosTablaRol() {
        this.txRlId.setText(this.jtRol.getValueAt(this.jtRol.getSelectedRow(), 1).toString());
        this.txRlDescripcion.setText(this.jtRol.getValueAt(this.jtRol.getSelectedRow(), 0).toString());     
    }
    public void devolverDatosTablaUsuario() {
        this.txRlId.setText(this.jtRol.getValueAt(this.jtRol.getSelectedRow(), 1).toString());
        this.txRlDescripcion.setText(this.jtRol.getValueAt(this.jtRol.getSelectedRow(), 0).toString());     
    }
    public void limpiarVentanaRol(){
        this.txRlId.setText("");
        this.txRlDescripcion.setText("");
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtRol = new javax.swing.JTable();
        btRlU = new javax.swing.JButton();
        btRlD = new javax.swing.JButton();
        txRlS = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txRlDescripcion = new javax.swing.JTextField();
        txRlId = new javax.swing.JTextField();
        btRlG = new javax.swing.JButton();
        btRlUPS = new javax.swing.JButton();
        btRlUPN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        btUsU = new javax.swing.JButton();
        btUsD = new javax.swing.JButton();
        txUsS = new javax.swing.JTextField();
        btRlUPS1 = new javax.swing.JButton();
        btRlUPN1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txUsCed = new javax.swing.JTextField();
        txUsId = new javax.swing.JTextField();
        btUsG = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txUsNom = new javax.swing.JTextField();
        txUsApe = new javax.swing.JTextField();
        txUsCor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txUsTel = new javax.swing.JTextField();
        txUsCon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txUsDir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txCopNom = new javax.swing.JTextField();
        txCopId = new javax.swing.JTextField();
        btCopG = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtCop = new javax.swing.JTable();
        btCopU = new javax.swing.JButton();
        btCopD = new javax.swing.JButton();
        txCopS = new javax.swing.JTextField();
        txCopRuc = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txCopDir = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txCopTel = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txCopCor = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txBusPla = new javax.swing.JTextField();
        txBusId = new javax.swing.JTextField();
        btBusG = new javax.swing.JButton();
        txBusAño = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txBusMar = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btBusU = new javax.swing.JButton();
        btBusD = new javax.swing.JButton();
        txBusS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBus = new javax.swing.JTable();
        cbBusCop = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();
        btClU = new javax.swing.JButton();
        btClD = new javax.swing.JButton();
        txClS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txClCed = new javax.swing.JTextField();
        txClId = new javax.swing.JTextField();
        btClG = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txClNom = new javax.swing.JTextField();
        txClApe = new javax.swing.JTextField();
        txClCor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txClTel = new javax.swing.JTextField();
        txClCon = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txClDir = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        txAsNum = new javax.swing.JTextField();
        txAsId = new javax.swing.JTextField();
        btAsG = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtAsiento = new javax.swing.JTable();
        btAsU = new javax.swing.JButton();
        btAsD = new javax.swing.JButton();
        txAsS = new javax.swing.JTextField();
        txAsUbi = new javax.swing.JTextField();
        Ubicacion = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbAsBus = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txRtId = new javax.swing.JTextField();
        btRtG = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtRuta = new javax.swing.JTable();
        btRtU = new javax.swing.JButton();
        btRtD = new javax.swing.JButton();
        txRtS = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txRtPpj = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txRtEst = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        cbRtBus = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cbRtUsu = new javax.swing.JComboBox<>();
        cbRtCO = new javax.swing.JComboBox<>();
        cbRtCD = new javax.swing.JComboBox<>();
        dcRtFhl = new com.toedter.calendar.JDateChooser();
        dcRtFhs = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCiudad = new javax.swing.JTable();
        btCiuU = new javax.swing.JButton();
        btCiuD = new javax.swing.JButton();
        txCiuS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txCiuNom = new javax.swing.JTextField();
        txCiuID = new javax.swing.JTextField();
        btCiuG = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txCiuCodPos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jtRol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtRol);

        btRlU.setText("Editar");
        btRlU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRlUActionPerformed(evt);
            }
        });

        btRlD.setText("Eliminar");
        btRlD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRlDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btRlU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRlD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txRlS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRlU)
                    .addComponent(btRlD)
                    .addComponent(txRlS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 287, -1));

        jLabel15.setText("Id");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 19, -1, -1));

        jLabel16.setText("Descripcion");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 19, -1, -1));
        jPanel7.add(txRlDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 16, 169, -1));
        jPanel7.add(txRlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, -1, -1));

        btRlG.setText("Guardar");
        btRlG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRlGActionPerformed(evt);
            }
        });
        jPanel7.add(btRlG, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 42, -1, -1));

        btRlUPS.setText("S");
        btRlUPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRlUPSActionPerformed(evt);
            }
        });
        jPanel7.add(btRlUPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 50, -1));

        btRlUPN.setText("N");
        jPanel7.add(btRlUPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtUsuario);

        btUsU.setText("Editar");

        btUsD.setText("Eliminar");
        btUsD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsDActionPerformed(evt);
            }
        });

        btRlUPS1.setText("S");
        btRlUPS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRlUPS1ActionPerformed(evt);
            }
        });

        btRlUPN1.setText("N");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btUsU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUsD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRlUPS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btRlUPN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txUsS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btUsU)
                        .addComponent(btUsD)
                        .addComponent(txUsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btRlUPS1)
                    .addComponent(btRlUPN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 910, 220));

        jLabel3.setText("Id");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 20, -1, -1));

        jLabel4.setText("Cedula");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel3.add(txUsCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, -1));
        jPanel3.add(txUsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 17, 10, -1));

        btUsG.setText("Guardar");
        btUsG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsGActionPerformed(evt);
            }
        });
        jPanel3.add(btUsG, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        jLabel5.setText("Nombre");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel6.setText("Apellido");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));
        jPanel3.add(txUsNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 120, -1));
        jPanel3.add(txUsApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, -1));
        jPanel3.add(txUsCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 130, -1));

        jLabel7.setText("Correo");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel8.setText("Telefono");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));
        jPanel3.add(txUsTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, -1));
        jPanel3.add(txUsCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, -1));

        jLabel9.setText("Direccion");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel10.setText("Contraseña");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel3.add(txUsDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 330, -1));

        jLabel11.setText("Rol");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        cbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolActionPerformed(evt);
            }
        });
        jPanel3.add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 120, -1));

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Cooperativa"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Id");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 19, -1, -1));

        jLabel18.setText("Nombre");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        jPanel9.add(txCopNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 130, -1));
        jPanel9.add(txCopId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 10, -1));

        btCopG.setText("Guardar");
        btCopG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCopGActionPerformed(evt);
            }
        });
        jPanel9.add(btCopG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jtCop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jtCop);

        btCopU.setText("Editar");

        btCopD.setText("Eliminar");
        btCopD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCopDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btCopU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCopD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txCopS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCopU)
                    .addComponent(btCopD)
                    .addComponent(txCopS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 760, 210));
        jPanel9.add(txCopRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, -1));

        jLabel28.setText("RUC");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));
        jPanel9.add(txCopDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 420, -1));

        jLabel29.setText("Direccion");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel9.add(txCopTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, -1));

        jLabel30.setText("Telefono");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));
        jPanel9.add(txCopCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 160, -1));

        jLabel31.setText("Correo");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bus"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 19, -1, -1));

        jLabel2.setText("Placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 19, -1, -1));
        jPanel1.add(txBusPla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, -1));
        jPanel1.add(txBusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 25, -1));

        btBusG.setText("Guardar");
        btBusG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusGActionPerformed(evt);
            }
        });
        jPanel1.add(btBusG, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));
        jPanel1.add(txBusAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 73, -1));

        jLabel32.setText("Año");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        jPanel1.add(txBusMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 74, -1));

        jLabel33.setText("Marca");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel35.setText("Cooperativa");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btBusU.setText("Editar");
        btBusU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusUActionPerformed(evt);
            }
        });

        btBusD.setText("Eliminar");
        btBusD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBusDActionPerformed(evt);
            }
        });

        jtBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtBus);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btBusU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBusD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txBusS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBusU)
                    .addComponent(btBusD)
                    .addComponent(txBusS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, 430, 210));

        jPanel1.add(cbBusCop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, -1));

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jtCliente);

        btClU.setText("Editar");

        btClD.setText("Eliminar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btClU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btClD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txClS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClU)
                    .addComponent(btClD)
                    .addComponent(txClS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 740, 160));

        jLabel19.setText("Id");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 19, -1, -1));

        jLabel20.setText("Cedula");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 19, -1, -1));
        jPanel11.add(txClCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 16, 90, -1));
        jPanel11.add(txClId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 10, -1));

        btClG.setText("Guardar");
        btClG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClGActionPerformed(evt);
            }
        });
        jPanel11.add(btClG, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jLabel21.setText("Nombre");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel22.setText("Apellido");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));
        jPanel11.add(txClNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));
        jPanel11.add(txClApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 20, 100, -1));
        jPanel11.add(txClCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        jLabel23.setText("Correo");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel24.setText("Telefono");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        txClTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txClTelActionPerformed(evt);
            }
        });
        jPanel11.add(txClTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 20, 100, -1));
        jPanel11.add(txClCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 100, -1));

        jLabel25.setText("Direccion");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel26.setText("Contraseña");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));
        jPanel11.add(txClDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 150, -1));

        jPanel13.setBackground(new java.awt.Color(204, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Asiento"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Id");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 19, -1, -1));

        Numero.setText("Numero");
        jPanel13.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
        jPanel13.add(txAsNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 20, 90, -1));
        jPanel13.add(txAsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 10, -1));

        btAsG.setText("Guardar");
        btAsG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsGActionPerformed(evt);
            }
        });
        jPanel13.add(btAsG, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jtAsiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jtAsiento);

        btAsU.setText("Editar");

        btAsD.setText("Eliminar");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(btAsU)
                        .addGap(20, 20, 20)
                        .addComponent(btAsD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txAsS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAsU)
                    .addComponent(btAsD)
                    .addComponent(txAsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 440, 160));
        jPanel13.add(txAsUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 50, 140, -1));

        Ubicacion.setText("Ubicacion");
        jPanel13.add(Ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel37.setText("Bus");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel13.add(cbAsBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, -1));

        jPanel17.setBackground(new java.awt.Color(204, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setText("Id");
        jPanel17.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, -1, -1));

        jLabel47.setText("Fecha y hora salida");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));
        jPanel17.add(txRtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, 10, -1));

        btRtG.setText("Guardar");
        btRtG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRtGActionPerformed(evt);
            }
        });
        jPanel17.add(btRtG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jtRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jtRuta);

        btRtU.setText("Editar");

        btRtD.setText("Eliminar");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(btRtU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRtD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txRtS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRtU)
                    .addComponent(btRtD)
                    .addComponent(txRtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 760, 230));

        jLabel48.setText("Fecha y hora llegada");
        jPanel17.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
        jPanel17.add(txRtPpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 100, -1));

        jLabel49.setText("Precio Pasaje");
        jPanel17.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));
        jPanel17.add(txRtEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 20, 110, -1));

        jLabel50.setText("Estado");
        jPanel17.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel51.setText("Bus");
        jPanel17.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel17.add(cbRtBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 90, 160, -1));

        jLabel34.setText("Usuario");
        jPanel17.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel36.setText("Ciudad Origen");
        jPanel17.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 26));

        jLabel38.setText("Ciudad Destino");
        jPanel17.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jPanel17.add(cbRtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 160, -1));

        jPanel17.add(cbRtCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 180, -1));

        jPanel17.add(cbRtCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 180, -1));
        jPanel17.add(dcRtFhl, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 20, 130, -1));
        jPanel17.add(dcRtFhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 130, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciudad"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jtCiudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtCiudad);

        btCiuU.setText("Editar");

        btCiuD.setText("Eliminar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btCiuU)
                        .addGap(18, 18, 18)
                        .addComponent(btCiuD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txCiuS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCiuU)
                    .addComponent(txCiuS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCiuD, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 45, 410, 320));

        jLabel12.setText("Id");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jLabel13.setText("Nombre");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        jPanel5.add(txCiuNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 17, 80, -1));
        jPanel5.add(txCiuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 17, 10, -1));

        btCiuG.setText("Guardar");
        btCiuG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCiuGActionPerformed(evt);
            }
        });
        jPanel5.add(btCiuG, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 16, 80, -1));

        jLabel14.setText("Codigo Postal");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));
        jPanel5.add(txCiuCodPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 17, 60, -1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel15Layout.createSequentialGroup()
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel15Layout.createSequentialGroup()
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane8.setViewportView(jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolActionPerformed

    }//GEN-LAST:event_cbRolActionPerformed

    private void btBusGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusGActionPerformed
        Controlador con = new Controlador();
        con.crearBus(this.txBusPla.getText(), Integer.parseInt(this.txBusAño.getText()), 
                this.txBusMar.getText(), 
                this.cbBusCop.getItemAt(this.cbBusCop.getSelectedIndex()));
        cargarTablas();
        cargarComboBox();

    }//GEN-LAST:event_btBusGActionPerformed

    private void btUsGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsGActionPerformed

        // paso 5 cargar desde el controlador el metodo para crear el objeto en cuestion
        Controlador con = new Controlador();
        con.crearUsuario(this.txUsCed.getText(), this.txUsNom.getText(),
                this.txUsApe.getText(), this.txUsTel.getText(),
                this.txUsCor.getText(), this.txUsDir.getText(),
                this.txUsCon.getText(),
                this.cbRol.getItemAt(this.cbRol.getSelectedIndex()));

        cargarTablas();
        cargarComboBox();


    }//GEN-LAST:event_btUsGActionPerformed

    private void btCiuGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCiuGActionPerformed
        Controlador con = new Controlador();
        con.crearCiudad(this.txCiuNom.getText(), this.txCiuCodPos.getText());
        cargarTablas();
        cargarComboBox();
    }//GEN-LAST:event_btCiuGActionPerformed

    private void btRlGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRlGActionPerformed
        Controlador con = new Controlador();
        con.crearRol(this.txRlDescripcion.getText());
        cargarTablas();
        cargarComboBox();

    }//GEN-LAST:event_btRlGActionPerformed

    private void btCopGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCopGActionPerformed
        Controlador con = new Controlador();
        con.crearCooperativa(this.txCopNom.getText(),
                this.txCopRuc.getText(),
                this.txCopDir.getText(),
                this.txCopTel.getText(),
                this.txCopCor.getText());
        cargarTablas();
        cargarComboBox();

    }//GEN-LAST:event_btCopGActionPerformed

    private void btClGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClGActionPerformed
Controlador con = new Controlador();
        con.crearCliente(this.txClCed.getText(), this.txClNom.getText(),
                this.txClApe.getText(), this.txClTel.getText(),
                this.txClCor.getText(), this.txClDir.getText(),
                this.txClCon.getText());

        cargarTablas();
        cargarComboBox();     
        
        
        
    }//GEN-LAST:event_btClGActionPerformed

    private void txClTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txClTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txClTelActionPerformed

    private void btRtGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRtGActionPerformed
        Controlador con = new Controlador();
        con.crearRuta(this.dcRtFhs.getCalendar().getTime(),this.dcRtFhl.getCalendar().getTime(),
                Double.parseDouble(this.txRtPpj.getText()),this.txRtEst.getText(),
               this.cbRtBus.getItemAt(this.cbRtBus.getSelectedIndex()),
               this.cbRtUsu.getItemAt(this.cbRtUsu.getSelectedIndex()),
               this.cbRtCO.getItemAt(this.cbRtCO.getSelectedIndex()),
               this.cbRtCD.getItemAt(this.cbRtCD.getSelectedIndex()));

        cargarTablas();
        cargarComboBox();
    }//GEN-LAST:event_btRtGActionPerformed

    private void btAsGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsGActionPerformed

        Controlador con = new Controlador();
        con.crearAsiento(this.txAsNum.getText(),
                this.txAsUbi.getText(), 
                this.cbAsBus.getItemAt(this.cbAsBus.getSelectedIndex()));

        cargarTablas();
        cargarComboBox();   
        
        
    }//GEN-LAST:event_btAsGActionPerformed

    private void btRlDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRlDActionPerformed
        Controlador ct= new Controlador();
        int id= Integer.parseInt(this.jtRol.getValueAt(this.jtRol.getSelectedRow(), 1).toString());
        ct.eliminarRol(id);
        cargarTablas();
        cargarComboBox(); 
    }//GEN-LAST:event_btRlDActionPerformed

    private void btRlUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRlUActionPerformed
        devolverDatosTablaRol();
    }//GEN-LAST:event_btRlUActionPerformed

    private void btRlUPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRlUPSActionPerformed
        Controlador ct= new Controlador();
        ct.actualizarRol(Integer.parseInt(this.txRlId.getText()), this.txRlDescripcion.getText());
        cargarTablas();
        cargarComboBox(); 
        limpiarVentanaRol();
    }//GEN-LAST:event_btRlUPSActionPerformed

    private void btRlUPS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRlUPS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRlUPS1ActionPerformed

    private void btUsDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsDActionPerformed
       Controlador ct= new Controlador();
        int id= Integer.parseInt(this.jtUsuario.getValueAt(this.jtUsuario.getSelectedRow(), 8).toString());
        ct.eliminarUsuario(id);
        cargarTablas();
        cargarComboBox(); 
    }//GEN-LAST:event_btUsDActionPerformed

    private void btCopDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCopDActionPerformed
        Controlador ct= new Controlador();
        int id= Integer.parseInt(this.jtCop.getValueAt(this.jtCop.getSelectedRow(), 5).toString());
        ct.eliminarCooperativa(id);
        cargarTablas();
        cargarComboBox(); 
    }//GEN-LAST:event_btCopDActionPerformed

    private void btBusUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusUActionPerformed
        
    }//GEN-LAST:event_btBusUActionPerformed

    private void btBusDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusDActionPerformed
        Controlador ct= new Controlador();
        int id= Integer.parseInt(this.jtBus.getValueAt(this.jtBus.getSelectedRow(), 4).toString());
        ct.eliminarBus(id);
        cargarTablas();
        cargarComboBox(); 
    }//GEN-LAST:event_btBusDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Ubicacion;
    private javax.swing.JButton btAsD;
    private javax.swing.JButton btAsG;
    private javax.swing.JButton btAsU;
    private javax.swing.JButton btBusD;
    private javax.swing.JButton btBusG;
    private javax.swing.JButton btBusU;
    private javax.swing.JButton btCiuD;
    private javax.swing.JButton btCiuG;
    private javax.swing.JButton btCiuU;
    private javax.swing.JButton btClD;
    private javax.swing.JButton btClG;
    private javax.swing.JButton btClU;
    private javax.swing.JButton btCopD;
    private javax.swing.JButton btCopG;
    private javax.swing.JButton btCopU;
    private javax.swing.JButton btRlD;
    private javax.swing.JButton btRlG;
    private javax.swing.JButton btRlU;
    private javax.swing.JButton btRlUPN;
    private javax.swing.JButton btRlUPN1;
    private javax.swing.JButton btRlUPS;
    private javax.swing.JButton btRlUPS1;
    private javax.swing.JButton btRtD;
    private javax.swing.JButton btRtG;
    private javax.swing.JButton btRtU;
    private javax.swing.JButton btUsD;
    private javax.swing.JButton btUsG;
    private javax.swing.JButton btUsU;
    private javax.swing.JComboBox<Bus> cbAsBus;
    private javax.swing.JComboBox<Cooperativa> cbBusCop;
    private javax.swing.JComboBox<Rol> cbRol;
    private javax.swing.JComboBox<Bus> cbRtBus;
    private javax.swing.JComboBox<Ciudad> cbRtCD;
    private javax.swing.JComboBox<Ciudad> cbRtCO;
    private javax.swing.JComboBox<Usuario> cbRtUsu;
    private com.toedter.calendar.JDateChooser dcRtFhl;
    private com.toedter.calendar.JDateChooser dcRtFhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jtAsiento;
    private javax.swing.JTable jtBus;
    private javax.swing.JTable jtCiudad;
    private javax.swing.JTable jtCliente;
    private javax.swing.JTable jtCop;
    private javax.swing.JTable jtRol;
    private javax.swing.JTable jtRuta;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JTextField txAsId;
    private javax.swing.JTextField txAsNum;
    private javax.swing.JTextField txAsS;
    private javax.swing.JTextField txAsUbi;
    private javax.swing.JTextField txBusAño;
    private javax.swing.JTextField txBusId;
    private javax.swing.JTextField txBusMar;
    private javax.swing.JTextField txBusPla;
    private javax.swing.JTextField txBusS;
    private javax.swing.JTextField txCiuCodPos;
    private javax.swing.JTextField txCiuID;
    private javax.swing.JTextField txCiuNom;
    private javax.swing.JTextField txCiuS;
    private javax.swing.JTextField txClApe;
    private javax.swing.JTextField txClCed;
    private javax.swing.JTextField txClCon;
    private javax.swing.JTextField txClCor;
    private javax.swing.JTextField txClDir;
    private javax.swing.JTextField txClId;
    private javax.swing.JTextField txClNom;
    private javax.swing.JTextField txClS;
    private javax.swing.JTextField txClTel;
    private javax.swing.JTextField txCopCor;
    private javax.swing.JTextField txCopDir;
    private javax.swing.JTextField txCopId;
    private javax.swing.JTextField txCopNom;
    private javax.swing.JTextField txCopRuc;
    private javax.swing.JTextField txCopS;
    private javax.swing.JTextField txCopTel;
    private javax.swing.JTextField txRlDescripcion;
    private javax.swing.JTextField txRlId;
    private javax.swing.JTextField txRlS;
    private javax.swing.JTextField txRtEst;
    private javax.swing.JTextField txRtId;
    private javax.swing.JTextField txRtPpj;
    private javax.swing.JTextField txRtS;
    private javax.swing.JTextField txUsApe;
    private javax.swing.JTextField txUsCed;
    private javax.swing.JTextField txUsCon;
    private javax.swing.JTextField txUsCor;
    private javax.swing.JTextField txUsDir;
    private javax.swing.JTextField txUsId;
    private javax.swing.JTextField txUsNom;
    private javax.swing.JTextField txUsS;
    private javax.swing.JTextField txUsTel;
    // End of variables declaration//GEN-END:variables
}
